### PR TITLE
MS-1915 - IATA: Adjust address labels to fit requested PDF

### PR DESCRIPTION
**Pull request by doompling**
- [x] new IATA label template

### CODE REVIEW

**Comment by doompling** [comment]
@thejayvm can I get a quick review on this when you have a chance?

**Comment by jasonewall** [comment]
Looks legit. :ship:

.... how does this get deployed? Gem?

**Comment by doompling** [comment]
In Measure's gemfile we have `gem 'pdf-labels', :git => 'https://github.com/yardstick/PDF-Labels.git', :require => 'pdf/label'`, so I think as long as master on this repo is updated when we deploy `bundle` should pickup the changes.

**Comment by jasonewall** [comment]
Right. Yeah. I saw that after I posted. We need to `bundle update pdf-labels` in the measure repo so `Gemfile.lock` gets updated with the new git hash.

**Pull request merged**
